<?php
/* Template Name: Shane */
get_header();
?>

<main class="mx-auto p-4 sm:p-6 lg:p-8">
    <!-- Banner Section -->
    <section class="relative w-full h-22 bg-gray-800 flex items-center justify-center text-white text-center rounded-lg">
        <div>
            <h1 class="text-4xl font-semibold italic">Shane Zimmerman</h1>
            <p class="text-lg mt-2"></p>
        </div>
    </section>

    <!-- Profile Picture & Basic Info -->
    <section class="flex flex-col items-center text-center">
        <img src="https://maizecoopsc.web.illinois.edu/wp-content/uploads/2024/04/shane.jpg" alt="Profile Picture" class="rounded-lg shadow-lg border-4 border-white h-60 w-60 object-cover">
        <h2 class="text-2xl font-semibold mt-4">Maize Geneticist</h2>
        <p class="text-gray-600 mt-2">Email: <a href="sazimmer@uiuc.edu" class="text-blue-500 hover:underline">sazimmer@uiuc.edu</a></p>
        
        <!-- Social Media Links -->
        <div class="flex space-x-4 mt-4">
            <a href="#" class="text-blue-600 hover:text-blue-800"><i class="fab fa-facebook text-2xl"></i></a>
            <a href="#" class="text-blue-500 hover:text-blue-700"><i class="fab fa-linkedin text-2xl"></i></a>
            <a href="#" class="text-blue-400 hover:text-blue-600"><i class="fab fa-twitter text-2xl"></i></a>
        </div>
    </section>

    <!-- About Section -->
    <section class="bg-white p-6 shadow-md rounded-lg">
        <h2 class="text-3xl font-semibold">Background</h2>
        <ul class="list-disc list-inside mt-4 text-gray-700 space-y-2">
            <li>B.Sc., University of Illinois, 5/21/92</li>
            <li>Certified Crop Advisor 2/96</li>
        </ul>
    </section>

    <!-- Research Section -->
    <section class="bg-white p-6 shadow-md rounded-lg">
        <h2 class="text-3xl font-semibold">About</h2>
        <p class="text-gray-700 mt-4">
            I joined the Maize Genetics Coopertion - Stock Center in February of 1999 as part of the NSF project Maize Gene Discovery, DNA Sequencing, and Phenotypic Analysis. My duties include the cataloging and maintainance of the mutant stocks generated by the RescueMu system, in this research program, and making these stocks readily available to the maize genetics community.
        </p>
        <p class="text-gray-700 mt-4">
            Along with this work, I also assist the other staff members in the functions of the Coop. These functions include planting and pollinating of Coop materials, along with helping to increase seed supplies of various seed collections. I also assist in the phenotypic analysis of seedling traits in sand benches, and the cataloging and data recording of other seed stock collections available at the Coop.
        </p>

        <p class="text-gray-700 mt-4">Zimmerman, S.A. and J.K. Pataky. 1992.Inoculation techniques to produce galls of common smut on ears of sweet corn. Phytopathology 82:995.</p>
    
    </section>

    <!-- Role & Responsibilities -->
    <!-- <section class="bg-white p-6 shadow-md rounded-lg">
        <h2 class="text-3xl font-semibold">Role & Responsibilities</h2>
        <p class="text-gray-700 mt-4">
            Acting as a liaison between commercial blueberry growers and university researchers.
            Communicating new developments in breeding, pathology, and horticultural sciences to the community.
        </p>
    </section> -->
</main>

<?php get_footer(); ?>
